// src/features/personal-research-works/mock-data/personalResearchWorksMockData.ts
import type {
  PersonalStatsDTO,
  PersonalWorkDetailDTO,
  PersonalWorkRowDTO,
  PersonalWorkStatusCodeDTO,
} from "../contracts/personalResearchWorksContracts";

const nowIso = () => new Date().toISOString();

function daysAgoIso(daysAgo: number): string {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
}

const STATUS_NAME: Record<PersonalWorkStatusCodeDTO, string> = {
  draft: "Bản nháp",
  submitted: "Chờ duyệt",
  approved: "Đã duyệt",
  rejected: "Bị từ chối",
};

export const personalWorksMock = (() => {
  // NOTE: mock current lecturer
  const current_lecturer_id = 101;

  const rows: PersonalWorkRowDTO[] = [
    {
      activity_id: 1,
      activity_code: "RA-2025-0001",
      title: "Bài báo về tối ưu hóa truy vấn trong hệ thống SPNC",
      kind_id: 1,
      kind_name: "Bài báo",
      type_id: 11,
      type_name: "Tạp chí",
      academic_year_id: 3,
      academic_year_code: "2024-2025",
      status_id: 3,
      status_code: "approved",
      status_name: STATUS_NAME.approved,
      work_year: 2025,
      venue_name: "Journal of Software Engineering",
      member_role_id: 1,
      member_role_name: "Chủ nhiệm",
      lecturer_hours: "45.00",
      submitted_at: daysAgoIso(60),
      approved_at: daysAgoIso(20),
      updated_at: daysAgoIso(18),
    },
    {
      activity_id: 2,
      activity_code: "RA-2025-0002",
      title: "Tham dự hội thảo quốc tế về AI ứng dụng",
      kind_id: 4,
      kind_name: "Hội thảo",
      type_id: 44,
      type_name: "Tham dự",
      academic_year_id: 3,
      academic_year_code: "2024-2025",
      status_id: 2,
      status_code: "submitted",
      status_name: STATUS_NAME.submitted,
      work_year: 2025,
      venue_name: "International Conference on Applied AI",
      member_role_id: 2,
      member_role_name: "Thành viên",
      lecturer_hours: null,
      submitted_at: daysAgoIso(8),
      approved_at: null,
      updated_at: daysAgoIso(7),
    },
    {
      activity_id: 3,
      activity_code: "RA-2025-0003",
      title: "Sách tham khảo: Kiến trúc phần mềm hiện đại",
      kind_id: 2,
      kind_name: "Sách",
      type_id: 22,
      type_name: "Tham khảo",
      academic_year_id: 3,
      academic_year_code: "2024-2025",
      status_id: 4,
      status_code: "rejected",
      status_name: STATUS_NAME.rejected,
      work_year: 2024,
      venue_name: "NXB Khoa học & Kỹ thuật",
      member_role_id: 1,
      member_role_name: "Chủ nhiệm",
      lecturer_hours: null,
      submitted_at: daysAgoIso(30),
      approved_at: null,
      updated_at: daysAgoIso(26),
    },
    {
      activity_id: 4,
      activity_code: "RA-2025-0004",
      title: "Đề tài cấp cơ sở: Tối ưu hóa luồng duyệt NCKH",
      kind_id: 3,
      kind_name: "Đề tài",
      type_id: 33,
      type_name: "Cơ sở",
      academic_year_id: 3,
      academic_year_code: "2024-2025",
      status_id: 1,
      status_code: "draft",
      status_name: STATUS_NAME.draft,
      work_year: 2025,
      venue_name: "SPNC Lab",
      member_role_id: 1,
      member_role_name: "Chủ nhiệm",
      lecturer_hours: null,
      submitted_at: null,
      approved_at: null,
      updated_at: daysAgoIso(2),
    },
    {
      activity_id: 5,
      activity_code: "RA-2025-0005",
      title: "Bài báo: Đánh giá hiệu năng hệ thống quản lý giờ NCKH",
      kind_id: 1,
      kind_name: "Bài báo",
      type_id: 12,
      type_name: "Hội nghị",
      academic_year_id: 2,
      academic_year_code: "2023-2024",
      status_id: 3,
      status_code: "approved",
      status_name: STATUS_NAME.approved,
      work_year: 2024,
      venue_name: "Proceedings of EduTech",
      member_role_id: 2,
      member_role_name: "Thành viên",
      lecturer_hours: "18.00",
      submitted_at: daysAgoIso(220),
      approved_at: daysAgoIso(180),
      updated_at: daysAgoIso(175),
    },
  ];

  const detailsById: Record<number, PersonalWorkDetailDTO> = {
    1: {
      activity_id: 1,
      activity_code: "RA-2025-0001",
      title: "Bài báo về tối ưu hóa truy vấn trong hệ thống SPNC",
      abstract:
        "Nghiên cứu cải thiện hiệu năng truy vấn và tối ưu indexes cho nghiệp vụ NCKH.",
      kind_id: 1,
      kind_name: "Bài báo",
      type_id: 11,
      type_name: "Tạp chí",
      academic_year_id: 3,
      academic_year_code: "2024-2025",
      status_id: 3,
      status_code: "approved",
      status_name: STATUS_NAME.approved,
      work_year: 2025,
      venue_name: "Journal of Software Engineering",
      member_role_id: 1,
      member_role_name: "Chủ nhiệm",
      lecturer_hours: "45.00",
      submitted_at: daysAgoIso(60),
      approved_at: daysAgoIso(20),
      total_hours_calc: "60.00",
      rejection_note: null,
      authors: [
        {
          lecturer_id: current_lecturer_id,
          lecturer_full_name: "Nguyễn Văn A",
          member_role_id: 1,
          member_role_name: "Chủ nhiệm",
          department_name: "CNTT",
          contribution_share: "0.6000",
        },
        {
          lecturer_id: 102,
          lecturer_full_name: "Trần Thị B",
          member_role_id: 2,
          member_role_name: "Thành viên",
          department_name: "CNTT",
          contribution_share: "0.4000",
        },
      ],
      evidence_items: [
        {
          evidence_file_id: 501,
          file_type_id: 1,
          file_type_name: "Nội dung",
          disk: "s3",
          path: "evidence/ra-2025-0001/content.pdf",
          original_name: "paper-content.pdf",
          mime_type: "application/pdf",
          size_bytes: 1_245_330,
          uploaded_at: daysAgoIso(58),
        },
      ],
      approvals: [
        {
          stage_code: "assistant",
          stage_name: "Khoa",
          status: "approved",
          decided_by_user_id: 9001,
          decided_by_user_name: "Trưởng khoa",
          decided_at: daysAgoIso(25),
          note: "Hồ sơ đầy đủ.",
        },
        {
          stage_code: "manager",
          stage_name: "Trường",
          status: "approved",
          decided_by_user_id: 9002,
          decided_by_user_name: "Phòng QLKH",
          decided_at: daysAgoIso(20),
          note: "Phê duyệt.",
        },
      ],
      status_histories: [
        {
          acted_at: daysAgoIso(60),
          acted_by_user_id: 8001,
          acted_by_user_name: "Nguyễn Văn A",
          from_status_code: "draft",
          to_status_code: "submitted",
          note: null,
        },
        {
          acted_at: daysAgoIso(20),
          acted_by_user_id: 9002,
          acted_by_user_name: "Phòng QLKH",
          from_status_code: "submitted",
          to_status_code: "approved",
          note: null,
        },
      ],
    },

    2: {
      activity_id: 2,
      activity_code: "RA-2025-0002",
      title: "Tham dự hội thảo quốc tế về AI ứng dụng",
      abstract: null,
      kind_id: 4,
      kind_name: "Hội thảo",
      type_id: 44,
      type_name: "Tham dự",
      academic_year_id: 3,
      academic_year_code: "2024-2025",
      status_id: 2,
      status_code: "submitted",
      status_name: STATUS_NAME.submitted,
      work_year: 2025,
      venue_name: "International Conference on Applied AI",
      member_role_id: 2,
      member_role_name: "Thành viên",
      lecturer_hours: null,
      submitted_at: daysAgoIso(8),
      approved_at: null,
      total_hours_calc: null,
      rejection_note: null,
      authors: [
        {
          lecturer_id: 201,
          lecturer_full_name: "Lê Văn C",
          member_role_id: 1,
          member_role_name: "Chủ nhiệm",
          department_name: "Khoa học dữ liệu",
          contribution_share: "0.7000",
        },
        {
          lecturer_id: current_lecturer_id,
          lecturer_full_name: "Nguyễn Văn A",
          member_role_id: 2,
          member_role_name: "Thành viên",
          department_name: "CNTT",
          contribution_share: "0.3000",
        },
      ],
      evidence_items: [
        {
          evidence_file_id: 510,
          file_type_id: 5,
          file_type_name: "Quyết định tham dự",
          disk: "s3",
          path: "evidence/ra-2025-0002/decision.pdf",
          original_name: "decision.pdf",
          mime_type: "application/pdf",
          size_bytes: 834_110,
          uploaded_at: daysAgoIso(8),
        },
      ],
      approvals: [
        {
          stage_code: "assistant",
          stage_name: "Khoa",
          status: "pending",
          decided_by_user_id: null,
          decided_by_user_name: null,
          decided_at: null,
          note: null,
        },
        {
          stage_code: "manager",
          stage_name: "Trường",
          status: "pending",
          decided_by_user_id: null,
          decided_by_user_name: null,
          decided_at: null,
          note: null,
        },
      ],
      status_histories: [
        {
          acted_at: daysAgoIso(8),
          acted_by_user_id: 8001,
          acted_by_user_name: "Nguyễn Văn A",
          from_status_code: "draft",
          to_status_code: "submitted",
          note: null,
        },
      ],
    },

    3: {
      activity_id: 3,
      activity_code: "RA-2025-0003",
      title: "Sách tham khảo: Kiến trúc phần mềm hiện đại",
      abstract:
        "Tổng hợp kiến thức kiến trúc phần mềm, microservices, event-driven và thực hành.",
      kind_id: 2,
      kind_name: "Sách",
      type_id: 22,
      type_name: "Tham khảo",
      academic_year_id: 3,
      academic_year_code: "2024-2025",
      status_id: 4,
      status_code: "rejected",
      status_name: STATUS_NAME.rejected,
      work_year: 2024,
      venue_name: "NXB Khoa học & Kỹ thuật",
      member_role_id: 1,
      member_role_name: "Chủ nhiệm",
      lecturer_hours: null,
      submitted_at: daysAgoIso(30),
      approved_at: null,
      total_hours_calc: null,
      rejection_note:
        "Thiếu minh chứng quyết định xuất bản / thông tin ISBN chưa rõ.",
      authors: [
        {
          lecturer_id: current_lecturer_id,
          lecturer_full_name: "Nguyễn Văn A",
          member_role_id: 1,
          member_role_name: "Chủ nhiệm",
          department_name: "CNTT",
          contribution_share: "1.0000",
        },
      ],
      evidence_items: [
        {
          evidence_file_id: 520,
          file_type_id: 2,
          file_type_name: "Bìa",
          disk: "s3",
          path: "evidence/ra-2025-0003/cover.png",
          original_name: "cover.png",
          mime_type: "image/png",
          size_bytes: 234_300,
          uploaded_at: daysAgoIso(30),
        },
      ],
      approvals: [
        {
          stage_code: "assistant",
          stage_name: "Khoa",
          status: "rejected",
          decided_by_user_id: 9001,
          decided_by_user_name: "Trưởng khoa",
          decided_at: daysAgoIso(26),
          note: "Thiếu file quyết định xuất bản.",
        },
        {
          stage_code: "manager",
          stage_name: "Trường",
          status: "pending",
          decided_by_user_id: null,
          decided_by_user_name: null,
          decided_at: null,
          note: null,
        },
      ],
      status_histories: [
        {
          acted_at: daysAgoIso(30),
          acted_by_user_id: 8001,
          acted_by_user_name: "Nguyễn Văn A",
          from_status_code: "draft",
          to_status_code: "submitted",
          note: null,
        },
        {
          acted_at: daysAgoIso(26),
          acted_by_user_id: 9001,
          acted_by_user_name: "Trưởng khoa",
          from_status_code: "submitted",
          to_status_code: "rejected",
          note: "Thiếu file quyết định xuất bản.",
        },
      ],
    },

    4: {
      activity_id: 4,
      activity_code: "RA-2025-0004",
      title: "Đề tài cấp cơ sở: Tối ưu hóa luồng duyệt NCKH",
      abstract: null,
      kind_id: 3,
      kind_name: "Đề tài",
      type_id: 33,
      type_name: "Cơ sở",
      academic_year_id: 3,
      academic_year_code: "2024-2025",
      status_id: 1,
      status_code: "draft",
      status_name: STATUS_NAME.draft,
      work_year: 2025,
      venue_name: "SPNC Lab",
      member_role_id: 1,
      member_role_name: "Chủ nhiệm",
      lecturer_hours: null,
      submitted_at: null,
      approved_at: null,
      total_hours_calc: null,
      rejection_note: null,
      authors: [
        {
          lecturer_id: 101,
          lecturer_full_name: "Nguyễn Văn A",
          member_role_id: 1,
          member_role_name: "Chủ nhiệm",
          department_name: "CNTT",
          contribution_share: "1.0000",
        },
      ],
      evidence_items: [],
      approvals: [],
      status_histories: [],
    },

    5: {
      activity_id: 5,
      activity_code: "RA-2025-0005",
      title: "Bài báo: Đánh giá hiệu năng hệ thống quản lý giờ NCKH",
      abstract: null,
      kind_id: 1,
      kind_name: "Bài báo",
      type_id: 12,
      type_name: "Hội nghị",
      academic_year_id: 2,
      academic_year_code: "2023-2024",
      status_id: 3,
      status_code: "approved",
      status_name: STATUS_NAME.approved,
      work_year: 2024,
      venue_name: "Proceedings of EduTech",
      member_role_id: 2,
      member_role_name: "Thành viên",
      lecturer_hours: "18.00",
      submitted_at: daysAgoIso(220),
      approved_at: daysAgoIso(180),
      total_hours_calc: "30.00",
      rejection_note: null,
      authors: [
        {
          lecturer_id: 300,
          lecturer_full_name: "Phạm Văn D",
          member_role_id: 1,
          member_role_name: "Chủ nhiệm",
          department_name: "KHTN",
          contribution_share: "0.4000",
        },
        {
          lecturer_id: 101,
          lecturer_full_name: "Nguyễn Văn A",
          member_role_id: 2,
          member_role_name: "Thành viên",
          department_name: "CNTT",
          contribution_share: "0.6000",
        },
      ],
      evidence_items: [],
      approvals: [
        {
          stage_code: "assistant",
          stage_name: "Khoa",
          status: "approved",
          decided_by_user_id: 9003,
          decided_by_user_name: "Phó trưởng khoa",
          decided_at: daysAgoIso(190),
          note: null,
        },
        {
          stage_code: "manager",
          stage_name: "Trường",
          status: "approved",
          decided_by_user_id: 9002,
          decided_by_user_name: "Phòng QLKH",
          decided_at: daysAgoIso(180),
          note: null,
        },
      ],
      status_histories: [],
    },
  };

  const recomputeStats = (
    inputRows: PersonalWorkRowDTO[]
  ): PersonalStatsDTO => {
    const total = inputRows.length;
    const approved = inputRows.filter(
      (r) => r.status_code === "approved"
    ).length;
    const pending = inputRows.filter(
      (r) => r.status_code === "submitted"
    ).length;
    const rejected = inputRows.filter(
      (r) => r.status_code === "rejected"
    ).length;
    const draft = inputRows.filter((r) => r.status_code === "draft").length;
    return {
      total_count: total,
      approved_count: approved,
      pending_count: pending,
      rejected_count: rejected,
      draft_count: draft,
    };
  };

  return {
    current_lecturer_id,
    rows,
    detailsById,
    recomputeStats,
    nowIso,
  };
})();
