// src/features/personal-research-works/services/personalResearchWorksService.ts
import type {
  PersonalStatsDTO,
  PersonalWorkDetailDTO,
  PersonalWorkFilterTabDTO,
  PersonalWorkRowDTO,
} from "../contracts/personalResearchWorksContracts";
import { personalWorksMock } from "../mock-data/personalResearchWorksMockData";

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function filterRowsByTab(
  rows: PersonalWorkRowDTO[],
  tab: PersonalWorkFilterTabDTO
): PersonalWorkRowDTO[] {
  if (tab === "all") return rows;
  return rows.filter((row) => row.status_code === tab);
}

let inMemoryRows: PersonalWorkRowDTO[] = [...personalWorksMock.rows];
let inMemoryDetails: Record<number, PersonalWorkDetailDTO> = {
  ...personalWorksMock.detailsById,
};

function nextActivityId(): number {
  const maxId = Math.max(...inMemoryRows.map((r) => r.activity_id), 0);
  return maxId + 1;
}

function buildActivityCode(id: number): string {
  // TODO(BE): activity_code should be generated by backend to guarantee uniqueness
  return `RA-2025-${String(id).padStart(4, "0")}`;
}

export const personalResearchWorksService = {
  async get_stats(): Promise<PersonalStatsDTO> {
    await delay(250);
    return personalWorksMock.recomputeStats(inMemoryRows);
  },

  async get_works_by_tab(
    tab: PersonalWorkFilterTabDTO
  ): Promise<PersonalWorkRowDTO[]> {
    await delay(350);
    const filtered = filterRowsByTab(inMemoryRows, tab);
    // Sort newest updated first
    return [...filtered].sort((a, b) => (a.updated_at < b.updated_at ? 1 : -1));
  },

  async get_work_detail(activity_id: number): Promise<PersonalWorkDetailDTO> {
    await delay(300);
    const detail = inMemoryDetails[activity_id];
    if (!detail) {
      throw new Error("Không tìm thấy chi tiết công trình (mock).");
    }
    return detail;
  },

  async copy_rejected_work(activity_id: number): Promise<PersonalWorkRowDTO> {
    await delay(400);

    const sourceRow = inMemoryRows.find((r) => r.activity_id === activity_id);
    if (!sourceRow) throw new Error("Không tìm thấy công trình để sao chép.");

    if (sourceRow.status_code !== "rejected") {
      throw new Error("Chỉ cho phép sao chép từ công trình bị từ chối.");
    }

    const newId = nextActivityId();
    const newCode = buildActivityCode(newId);
    const now = personalWorksMock.nowIso();

    const newRow: PersonalWorkRowDTO = {
      ...sourceRow,
      activity_id: newId,
      activity_code: newCode,
      title: `${sourceRow.title} (kê khai lại)`,
      status_id: 1,
      status_code: "draft",
      status_name: "Bản nháp",
      lecturer_hours: null,
      submitted_at: null,
      approved_at: null,
      updated_at: now,
    };

    inMemoryRows = [newRow, ...inMemoryRows];

    const sourceDetail = inMemoryDetails[activity_id];
    if (sourceDetail) {
      inMemoryDetails[newId] = {
        ...sourceDetail,
        activity_id: newId,
        activity_code: newCode,
        title: newRow.title,
        status_id: 1,
        status_code: "draft",
        status_name: "Bản nháp",
        lecturer_hours: null,
        submitted_at: null,
        approved_at: null,
        total_hours_calc: null,
        rejection_note: null,
        approvals: [],
        status_histories: [],
      };
    }

    return newRow;
  },

  async create_new_draft(): Promise<PersonalWorkRowDTO> {
    await delay(300);

    const newId = nextActivityId();
    const newCode = buildActivityCode(newId);
    const now = personalWorksMock.nowIso();

    // NOTE: title is required in schema (VARCHAR500, required) => mock must not be empty
    const row: PersonalWorkRowDTO = {
      activity_id: newId,
      activity_code: newCode,
      title: "Bản nháp mới",

      kind_id: 3,
      kind_name: "Đề tài",

      type_id: null,
      type_name: null,

      academic_year_id: 3,
      academic_year_code: "2024-2025",

      status_id: 1,
      status_code: "draft",
      status_name: "Bản nháp",

      work_year: 2025,
      venue_name: "—",

      member_role_id: 1,
      member_role_name: "Chủ nhiệm",

      lecturer_hours: null,

      submitted_at: null,
      approved_at: null,
      updated_at: now,
    };

    inMemoryRows = [row, ...inMemoryRows];

    inMemoryDetails[newId] = {
      activity_id: newId,
      activity_code: newCode,
      title: row.title,
      abstract: null,

      kind_id: row.kind_id,
      kind_name: row.kind_name,

      type_id: row.type_id,
      type_name: row.type_name,

      academic_year_id: row.academic_year_id,
      academic_year_code: row.academic_year_code,

      status_id: row.status_id,
      status_code: row.status_code,
      status_name: row.status_name,

      work_year: row.work_year,
      venue_name: row.venue_name,

      member_role_id: row.member_role_id,
      member_role_name: row.member_role_name,
      lecturer_hours: null,

      submitted_at: null,
      approved_at: null,
      total_hours_calc: null,

      rejection_note: null,
      authors: [
        {
          lecturer_id: personalWorksMock.current_lecturer_id,
          lecturer_full_name: "Nguyễn Văn A",
          member_role_id: 1,
          member_role_name: "Chủ nhiệm",
          department_name: "CNTT",
          contribution_share: "1.0000",
        },
      ],
      evidence_items: [],
      approvals: [],
      status_histories: [],
    };

    return row;
  },
};
