import type { WorkDetailDTO } from "../contracts/selectHoursRequest.contract";

export const workDetailsMockDTO: Record<number, WorkDetailDTO> = {
  101: {
    activity_id: 101,
    title: "AI trong giáo dục đại học",
    kind_name: "Bài báo",
    academic_year_code: "2024-2025",
    publication_or_unit: "Tạp chí Khoa học Giáo dục (mock)",
    member_role_name: "Tác giả",
    contribution_share: 0.6,
    rule_summary: "Bài báo: 100 giờ / bài (mock).",
    hours_for_lecturer: 40,
    activity_status_code: "approved",
    hours_request_state: "hours_not_submitted",
    next_action_code: "submit_hours",
    next_action_text: "Gửi duyệt giờ",
  },
  102: {
    activity_id: 102,
    title: "IoT cho y tế thông minh",
    kind_name: "Đề tài",
    academic_year_code: "2024-2025",
    publication_or_unit: "Mã đề tài: DT-2024-02 (mock)",
    member_role_name: "Chủ nhiệm",
    contribution_share: 1,
    rule_summary: "Đề tài: 120 giờ / đề tài (mock).",
    hours_for_lecturer: 60,
    activity_status_code: "approved",
    hours_request_state: "hours_pending_faculty",
    next_action_code: "wait_faculty",
    next_action_text: "Chờ khoa duyệt giờ",
  },
  103: {
    activity_id: 103,
    title: "Hội thảo chuyển đổi số 2025",
    kind_name: "Hội thảo",
    academic_year_code: "2024-2025",
    publication_or_unit: "Địa điểm: Hà Nội (mock)",
    member_role_name: "Thành viên",
    contribution_share: 0.4,
    rule_summary: "Hội thảo: 30 giờ / lần tham dự (mock).",
    hours_for_lecturer: 20,
    activity_status_code: "approved",
    hours_request_state: "hours_approved",
    next_action_code: "none",
    next_action_text: "Đã duyệt",
  },
  104: {
    activity_id: 104,
    title: "Giáo trình Nhập môn Khoa học Dữ liệu",
    kind_name: "Sách",
    academic_year_code: "2023-2024",
    publication_or_unit: "NXB Giáo dục (mock)",
    member_role_name: "Chủ biên",
    contribution_share: 0.8,
    rule_summary: "Sách/giáo trình: 200 giờ / cuốn (mock).",
    hours_for_lecturer: 80,
    activity_status_code: "approved",
    hours_request_state: "hours_rejected",
    hours_rejection_reason: "Thiếu biên bản nghiệm thu.",
    next_action_code: "resubmit_hours",
    next_action_text: "Điều chỉnh và gửi lại duyệt giờ",
  },
};
