import type {
  FacultyOption,
  LecturerSuggestion,
  ResearchWorkDetailDTO,
  ResearchWorkSummaryDTO,
} from "../contracts/globalResearchWorkSearch.contract";

export const facultyOptionsMock: FacultyOption[] = [
  { id: 1, name: "Công nghệ thông tin" },
  { id: 2, name: "Toán" },
  { id: 3, name: "Kinh tế" },
  { id: 4, name: "Sư phạm" },
  { id: 5, name: "Điện - Điện tử" },
];

export const lecturerSuggestionsMock: LecturerSuggestion[] = [
  {
    lecturer_id: 11,
    lecturer_code: "GV001",
    lecturer_name: "Nguyễn Văn A",
    faculty_name: "Công nghệ thông tin",
  },
  {
    lecturer_id: 12,
    lecturer_code: "GV014",
    lecturer_name: "Trần Thị B",
    faculty_name: "Toán",
  },
  {
    lecturer_id: 13,
    lecturer_code: "GV025",
    lecturer_name: "Lê Hoàng C",
    faculty_name: "Kinh tế",
  },
  {
    lecturer_id: 14,
    lecturer_code: "GV032",
    lecturer_name: "Phạm Minh D",
    faculty_name: "Sư phạm",
  },
  {
    lecturer_id: 15,
    lecturer_code: "GV041",
    lecturer_name: "Vũ Thanh E",
    faculty_name: "Điện - Điện tử",
  },
];

export const researchWorkSummariesMockDTO: ResearchWorkSummaryDTO[] = [
  {
    work_id: 1001,
    title: "AI trong giáo dục đại học",
    subtitle: "Tạp chí Khoa học Giáo dục (Q2) • DOI: 10.1234/mock.1001",
    type_key: "article",
    faculty_name: "Sư phạm",
    primary_lecturer_name: "Phạm Minh D",
    primary_lecturer_code: "GV032",
    year: 2025,
    status_code: "approved",
    has_public_pdf: true,
  },
  {
    work_id: 1002,
    title: "Mô hình dự báo chuỗi thời gian cho dữ liệu tài chính",
    subtitle: "Hội thảo FinTech 2024 • Hà Nội",
    type_key: "conference",
    faculty_name: "Kinh tế",
    primary_lecturer_name: "Lê Hoàng C",
    primary_lecturer_code: "GV025",
    year: 2024,
    status_code: "approved",
    has_public_pdf: false,
  },
  {
    work_id: 1003,
    title: "Hệ thống IoT giám sát môi trường trong đô thị",
    subtitle: "Đề tài cấp Trường • Mã số: DT-UNI-2024-07",
    type_key: "project",
    faculty_name: "Điện - Điện tử",
    primary_lecturer_name: "Vũ Thanh E",
    primary_lecturer_code: "GV041",
    year: 2024,
    status_code: "submitted",
    has_public_pdf: false,
  },
  {
    work_id: 1004,
    title: "Giáo trình Nhập môn Khoa học Dữ liệu",
    subtitle: "NXB Giáo dục • ISBN: 978-1-2345-6789-0",
    type_key: "book",
    faculty_name: "Công nghệ thông tin",
    primary_lecturer_name: "Nguyễn Văn A",
    primary_lecturer_code: "GV001",
    year: 2023,
    status_code: "approved",
    has_public_pdf: true,
  },
  {
    work_id: 1005,
    title: "Tối ưu hoá tuyến tính và ứng dụng",
    subtitle: "Sách tham khảo • NXB Đại học Quốc gia (mock)",
    type_key: "book",
    faculty_name: "Toán",
    primary_lecturer_name: "Trần Thị B",
    primary_lecturer_code: "GV014",
    year: 2022,
    status_code: "approved",
    has_public_pdf: false,
  },
  {
    work_id: 1006,
    title: "Đánh giá hiệu quả giảng dạy theo dữ liệu LMS",
    subtitle: "Tạp chí Giáo dục • Vol 12, No 3",
    type_key: "article",
    faculty_name: "Sư phạm",
    primary_lecturer_name: "Phạm Minh D",
    primary_lecturer_code: "GV032",
    year: 2024,
    status_code: "rejected",
    has_public_pdf: false,
  },
  {
    work_id: 1007,
    title: "Nghiên cứu hành vi tiêu dùng trên sàn TMĐT",
    subtitle: "Đề tài cấp Khoa • Kinh tế số (mock)",
    type_key: "project",
    faculty_name: "Kinh tế",
    primary_lecturer_name: "Lê Hoàng C",
    primary_lecturer_code: "GV025",
    year: 2025,
    status_code: "approved",
    has_public_pdf: true,
  },
  {
    work_id: 1008,
    title: "Tích hợp học máy cho phát hiện gian lận",
    subtitle: "Tạp chí CNTT • Q1 (mock)",
    type_key: "article",
    faculty_name: "Công nghệ thông tin",
    primary_lecturer_name: "Nguyễn Văn A",
    primary_lecturer_code: "GV001",
    year: 2025,
    status_code: "approved",
    has_public_pdf: true,
  },
  {
    work_id: 1009,
    title: "Hội thảo chuyển đổi số 2025",
    subtitle: "Digital Transformation Summit • TP.HCM",
    type_key: "conference",
    faculty_name: "Công nghệ thông tin",
    primary_lecturer_name: "Nguyễn Văn A",
    primary_lecturer_code: "GV001",
    year: 2025,
    status_code: "approved",
    has_public_pdf: false,
  },
  {
    work_id: 1010,
    title: "Thiết kế mạch công suất hiệu suất cao",
    subtitle: "Hội nghị EE 2023 • Đà Nẵng",
    type_key: "conference",
    faculty_name: "Điện - Điện tử",
    primary_lecturer_name: "Vũ Thanh E",
    primary_lecturer_code: "GV041",
    year: 2023,
    status_code: "approved",
    has_public_pdf: true,
  },
  {
    work_id: 1011,
    title: "Phương pháp số cho bài toán PDE",
    subtitle: "Tạp chí Toán học Ứng dụng • 2024",
    type_key: "article",
    faculty_name: "Toán",
    primary_lecturer_name: "Trần Thị B",
    primary_lecturer_code: "GV014",
    year: 2024,
    status_code: "approved",
    has_public_pdf: false,
  },
  {
    work_id: 1012,
    title: "Khảo sát động lực học cho hệ phi tuyến",
    subtitle: "Đề tài cấp Bộ (mock) • Mã: DT-MIN-2025-01",
    type_key: "project",
    faculty_name: "Toán",
    primary_lecturer_name: "Trần Thị B",
    primary_lecturer_code: "GV014",
    year: 2025,
    status_code: "approved",
    has_public_pdf: true,
  },
];

export const researchWorkDetailsMockDTO: Record<number, ResearchWorkDetailDTO> =
  {
    1001: {
      work_id: 1001,
      title: "AI trong giáo dục đại học",
      type_key: "article",
      status_code: "approved",
      year: 2025,
      abstract:
        "Nghiên cứu đề xuất mô hình ứng dụng AI trong đánh giá học tập và cá nhân hoá lộ trình học (mock).",
      info_rows: [
        {
          label: "Tạp chí/Hội thảo",
          value: "Tạp chí Khoa học Giáo dục (Q2) (mock)",
        },
        { label: "Số/Tập/Trang", value: "Vol 10, No 2, pp. 15–28 (mock)" },
        { label: "DOI", value: "10.1234/mock.1001" },
      ],
      participants: [
        {
          name: "Phạm Minh D",
          faculty_name: "Sư phạm",
          role_label: "Tác giả chính",
        },
        {
          name: "Nguyễn Văn A",
          faculty_name: "Công nghệ thông tin",
          role_label: "Đồng tác giả",
        },
      ],
      files: [
        {
          file_id: 1,
          kind: "pdf",
          label: "Bài báo (PDF)",
          url: "/mock-files/paper-1001.pdf",
        },
        {
          file_id: 2,
          kind: "link",
          label: "Trang tạp chí",
          url: "https://example.com/journal/1001",
        },
      ],
    },
    1004: {
      work_id: 1004,
      title: "Giáo trình Nhập môn Khoa học Dữ liệu",
      type_key: "book",
      status_code: "approved",
      year: 2023,
      abstract:
        "Giáo trình tổng hợp nền tảng dữ liệu, thống kê, và ML dành cho sinh viên (mock).",
      info_rows: [
        { label: "Nhà xuất bản", value: "NXB Giáo dục (mock)" },
        { label: "ISBN", value: "978-1-2345-6789-0" },
        { label: "Loại", value: "Giáo trình" },
      ],
      participants: [
        {
          name: "Nguyễn Văn A",
          faculty_name: "Công nghệ thông tin",
          role_label: "Chủ biên",
        },
        {
          name: "Lê Hoàng C",
          faculty_name: "Kinh tế",
          role_label: "Đồng tác giả",
        },
      ],
      files: [
        {
          file_id: 10,
          kind: "pdf",
          label: "Mục lục (PDF)",
          url: "/mock-files/book-1004.pdf",
        },
        {
          file_id: 11,
          kind: "link",
          label: "Trang NXB",
          url: "https://example.com/publisher/book-1004",
        },
      ],
    },
    1007: {
      work_id: 1007,
      title: "Nghiên cứu hành vi tiêu dùng trên sàn TMĐT",
      type_key: "project",
      status_code: "approved",
      year: 2025,
      abstract: null,
      info_rows: [
        { label: "Cấp quản lý", value: "Cấp Khoa" },
        { label: "Mã số đề tài", value: "DT-FAC-2025-03 (mock)" },
        { label: "Thời gian", value: "01/2025 – 10/2025 (mock)" },
      ],
      participants: [
        {
          name: "Lê Hoàng C",
          faculty_name: "Kinh tế",
          role_label: "Chủ nhiệm",
        },
        { name: "Trần Thị B", faculty_name: "Toán", role_label: "Thành viên" },
      ],
      files: [
        {
          file_id: 21,
          kind: "pdf",
          label: "Báo cáo tổng kết (PDF)",
          url: "/mock-files/project-1007.pdf",
        },
      ],
    },
    1010: {
      work_id: 1010,
      title: "Thiết kế mạch công suất hiệu suất cao",
      type_key: "conference",
      status_code: "approved",
      year: 2023,
      abstract:
        "Trình bày giải pháp nâng hiệu suất mạch công suất và tối ưu tản nhiệt (mock).",
      info_rows: [
        { label: "Hội nghị", value: "Hội nghị EE 2023 (mock)" },
        { label: "Địa điểm", value: "Đà Nẵng" },
        { label: "Thời gian", value: "09/2023 (mock)" },
      ],
      participants: [
        {
          name: "Vũ Thanh E",
          faculty_name: "Điện - Điện tử",
          role_label: "Báo cáo chính",
        },
        {
          name: "Nguyễn Văn A",
          faculty_name: "Công nghệ thông tin",
          role_label: "Thành viên",
        },
      ],
      files: [
        {
          file_id: 31,
          kind: "pdf",
          label: "Proceedings (PDF)",
          url: "/mock-files/conf-1010.pdf",
        },
        {
          file_id: 32,
          kind: "link",
          label: "Website hội nghị",
          url: "https://example.com/conf/1010",
        },
      ],
    },
    1012: {
      work_id: 1012,
      title: "Khảo sát động lực học cho hệ phi tuyến",
      type_key: "project",
      status_code: "approved",
      year: 2025,
      abstract: null,
      info_rows: [
        { label: "Cấp quản lý", value: "Cấp Bộ" },
        { label: "Mã số đề tài", value: "DT-MIN-2025-01 (mock)" },
        { label: "Thời gian", value: "02/2025 – 12/2025 (mock)" },
      ],
      participants: [
        { name: "Trần Thị B", faculty_name: "Toán", role_label: "Chủ nhiệm" },
        {
          name: "Phạm Minh D",
          faculty_name: "Sư phạm",
          role_label: "Thành viên",
        },
      ],
      files: [
        {
          file_id: 41,
          kind: "pdf",
          label: "Quyết định phê duyệt (PDF)",
          url: "/mock-files/project-1012.pdf",
        },
      ],
    },
  };
