<template>
  <ResearchWorkApprovalPageShell
    :ui-configuration="universityResearchWorkApprovalProvider.uiConfiguration"
    :page-title="universityResearchWorkApprovalProvider.pageTitle"
    :page-subtitle="universityResearchWorkApprovalProvider.pageSubtitle"
    :pending-badge-text="
      universityResearchWorkApprovalProvider.pendingBadgeText
    "
    :filter-panel-helper-text="
      universityResearchWorkApprovalProvider.filterPanelHelperText
    "
    :academic-year-options="
      universityResearchWorkApprovalProvider.academicYearOptions
    "
    :department-options="
      universityResearchWorkApprovalProvider.departmentOptions
    "
    :research-work-type-options="
      universityResearchWorkApprovalProvider.researchWorkTypeOptions
    "
    :approval-status-option-list="
      universityResearchWorkApprovalProvider.approvalStatusOptionList
    "
    v-model:selectedAcademicYear="
      universityResearchWorkApprovalProvider.selectedAcademicYear
    "
    v-model:selectedDepartmentIdentifier="
      universityResearchWorkApprovalProvider.selectedDepartmentIdentifier
    "
    v-model:selectedResearchWorkType="
      universityResearchWorkApprovalProvider.selectedResearchWorkType
    "
    v-model:selectedApprovalStatus="
      universityResearchWorkApprovalProvider.selectedApprovalStatus
    "
    v-model:selectedLecturerOrResearchWorkKeyword="
      universityResearchWorkApprovalProvider.selectedLecturerOrResearchWorkKeyword
    "
    :filtered-research-work-approval-list="
      universityResearchWorkApprovalProvider.filteredResearchWorkApprovalList
    "
    :total-pending-research-work-count="
      universityResearchWorkApprovalProvider.totalPendingResearchWorkCount
    "
    :is-detail-drawer-open="
      universityResearchWorkApprovalProvider.isDetailDrawerOpen
    "
    :selected-research-work-approval-entry="
      universityResearchWorkApprovalProvider.selectedResearchWorkApprovalEntry
    "
    :drawer-helper-text="
      universityResearchWorkApprovalProvider.drawerHelperText
    "
    :drawer-footer-helper-text="
      universityResearchWorkApprovalProvider.drawerFooterHelperText
    "
    :rejection-reason-option-list="
      universityResearchWorkApprovalProvider.rejectionReasonOptionList
    "
    @resetFilterConditions="
      universityResearchWorkApprovalProvider.resetFilterConditions
    "
    @openResearchWorkDetailDrawer="
      universityResearchWorkApprovalProvider.openResearchWorkDetailDrawer
    "
    @closeResearchWorkDetailDrawer="
      universityResearchWorkApprovalProvider.closeResearchWorkDetailDrawer
    "
    @approve="universityResearchWorkApprovalProvider.approve"
    @reject="universityResearchWorkApprovalProvider.reject"
  />
</template>

<script setup lang="ts">
import { proxyRefs } from "vue";
import ResearchWorkApprovalPageShell from "../../shared/components/ResearchWorkApprovalPageShell.vue";
import { useUniversityResearchWorkApprovalProvider } from "../composables/useUniversityResearchWorkApprovalProvider";

const universityResearchWorkApprovalProvider = proxyRefs(
  useUniversityResearchWorkApprovalProvider()
);
</script>
