import type { LecturerHoursOverviewDTO } from "../lecturerHours.contract";

const year_2024_2025 = { id: 1, code: "2024-2025" } as const;
const year_2023_2024 = { id: 2, code: "2023-2024" } as const;

const quotaByYearId: Record<number, number> = {
  [year_2024_2025.id]: 600,
  [year_2023_2024.id]: 580,
};

function resolveRequiredHours(academic_year_id: number): number {
  // IMPORTANT:
  // Nếu project bật `noUncheckedIndexedAccess`, index access => number | undefined
  // => luôn fallback để trả về number
  return quotaByYearId[academic_year_id] ?? 600;
}

export const mockLecturerHoursOverviewRows: LecturerHoursOverviewDTO[] = [
  // ===== Faculty 10: CNTT (>= 6 lecturers) =====
  {
    lecturer_id: 101,
    lecturer_code: "CNTT-001",
    lecturer_full_name: "Nguyễn Văn An",
    faculty_id: 10,
    faculty_name: "Khoa Công nghệ Thông tin",
    department_id: 1001,
    department_name: "Bộ môn Khoa học máy tính",
    degree_name: "Tiến sĩ",
    academic_rank_name: "PGS",
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 720,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },
  {
    lecturer_id: 102,
    lecturer_code: "CNTT-002",
    lecturer_full_name: "Trần Thị Bình",
    faculty_id: 10,
    faculty_name: "Khoa Công nghệ Thông tin",
    department_id: 1002,
    department_name: "Bộ môn Hệ thống thông tin",
    degree_name: "Thạc sĩ",
    academic_rank_name: null,
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 450,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },
  {
    lecturer_id: 103,
    lecturer_code: "CNTT-003",
    lecturer_full_name: "Lê Quốc Cường",
    faculty_id: 10,
    faculty_name: "Khoa Công nghệ Thông tin",
    department_id: 1001,
    department_name: "Bộ môn Khoa học máy tính",
    degree_name: "Thạc sĩ",
    academic_rank_name: null,
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 0,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },
  {
    lecturer_id: 104,
    lecturer_code: "CNTT-004",
    lecturer_full_name: "Phạm Gia Dũng",
    faculty_id: 10,
    faculty_name: "Khoa Công nghệ Thông tin",
    department_id: 1003,
    department_name: "Bộ môn Kỹ thuật phần mềm",
    degree_name: "Tiến sĩ",
    academic_rank_name: null,
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 590,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },
  {
    lecturer_id: 105,
    lecturer_code: "CNTT-005",
    lecturer_full_name: "Vũ Thị Em",
    faculty_id: 10,
    faculty_name: "Khoa Công nghệ Thông tin",
    department_id: 1002,
    department_name: "Bộ môn Hệ thống thông tin",
    degree_name: "Tiến sĩ",
    academic_rank_name: "GS",
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 900,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },
  {
    lecturer_id: 106,
    lecturer_code: "CNTT-006",
    lecturer_full_name: "Đặng Minh Hòa",
    faculty_id: 10,
    faculty_name: "Khoa Công nghệ Thông tin",
    department_id: 1003,
    department_name: "Bộ môn Kỹ thuật phần mềm",
    degree_name: null,
    academic_rank_name: null,
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 610,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },

  // ===== Faculty 20: Kinh tế =====
  {
    lecturer_id: 201,
    lecturer_code: "KTE-001",
    lecturer_full_name: "Hoàng Thị Hạnh",
    faculty_id: 20,
    faculty_name: "Khoa Kinh tế",
    department_id: 2001,
    department_name: "Bộ môn Kinh tế học",
    degree_name: "Tiến sĩ",
    academic_rank_name: null,
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 640,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },
  {
    lecturer_id: 202,
    lecturer_code: "KTE-002",
    lecturer_full_name: "Ngô Văn Khoa",
    faculty_id: 20,
    faculty_name: "Khoa Kinh tế",
    department_id: 2002,
    department_name: "Bộ môn Tài chính",
    degree_name: "Thạc sĩ",
    academic_rank_name: null,
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 520,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },
  {
    lecturer_id: 203,
    lecturer_code: "KTE-003",
    lecturer_full_name: "Bùi Thị Lan",
    faculty_id: 20,
    faculty_name: "Khoa Kinh tế",
    department_id: 2002,
    department_name: "Bộ môn Tài chính",
    degree_name: "Tiến sĩ",
    academic_rank_name: "PGS",
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 300,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },
  {
    lecturer_id: 204,
    lecturer_code: "KTE-004",
    lecturer_full_name: "Phan Quốc Minh",
    faculty_id: 20,
    faculty_name: "Khoa Kinh tế",
    department_id: 2003,
    department_name: "Bộ môn Quản trị",
    degree_name: "Thạc sĩ",
    academic_rank_name: null,
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 605,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },
  {
    lecturer_id: 205,
    lecturer_code: "KTE-005",
    lecturer_full_name: "Đỗ Thị Ngọc",
    faculty_id: 20,
    faculty_name: "Khoa Kinh tế",
    department_id: 2001,
    department_name: "Bộ môn Kinh tế học",
    degree_name: null,
    academic_rank_name: null,
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 0,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },
  {
    lecturer_id: 206,
    lecturer_code: "KTE-006",
    lecturer_full_name: "Tạ Văn Phúc",
    faculty_id: 20,
    faculty_name: "Khoa Kinh tế",
    department_id: 2003,
    department_name: "Bộ môn Quản trị",
    degree_name: "Tiến sĩ",
    academic_rank_name: null,
    academic_year_id: year_2024_2025.id,
    academic_year_code: year_2024_2025.code,
    hours_total: 780,
    required_hours: resolveRequiredHours(year_2024_2025.id),
  },

  // ===== record năm trước =====
  {
    lecturer_id: 101,
    lecturer_code: "CNTT-001",
    lecturer_full_name: "Nguyễn Văn An",
    faculty_id: 10,
    faculty_name: "Khoa Công nghệ Thông tin",
    department_id: 1001,
    department_name: "Bộ môn Khoa học máy tính",
    degree_name: "Tiến sĩ",
    academic_rank_name: "PGS",
    academic_year_id: year_2023_2024.id,
    academic_year_code: year_2023_2024.code,
    hours_total: 610,
    required_hours: resolveRequiredHours(year_2023_2024.id),
  },
];
